services:
  - type: web
    name: invoice-api
    env: node
    plan: free
    buildCommand: ./build.sh
    startCommand: npm start
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
